### ISSUE TITLE
allure report issue

### ISSUE THREAD

**Issue by siva90144** [AZANIR/Playwright_Cucumber_Allure#1]
Its throwing below error when trying to generate allure report

command used: USE_ALLURE=1 npm run test

its generated the some json, txt and csv files in reports/allure-results

now I executed this command **npm run allure** and throwing below error
`playwright-cucumber-allure@1.0.0 allure
> npx allure serve reports/allure-results

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in`

**Comment by AZANIR** [comment]
install `npm install allure-commandline`

**Comment by siva90144** [comment]
Thank You @AZANIR . But why do I need command line. i want to generate the report locally. when i try to open it its pointing too to some external server.

**Comment by AZANIR** [comment]
You generate a report using a console command, so this module is needed. Once generated, it creates a local server in the temporary folder for viewing, you can view it. if you click Control-C in the console, the server will be deleted instead of temporary files. This applies to the "allure" command: "npx allure serve reports/allure-results". If you just need to generate an HTML report then you need the command 
"npx allure generate reports/allure-results --clean", the finished report will be in the "allure-reports" folder

**Comment by siva90144** [comment]
@AZANIR so its secured right ? if i want to use in company does any info wont share in the server right

**Comment by AZANIR** [comment]
> @AZANIR so its secured right ? if i want to use in company does any info wont share in the server right

Yes it is secured
